name: previsao_tempo_delta

on:

  schedule:
    - cron: "30 11 * * *" 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:

          python-version: 3.10.2 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests beautifulsoup4 datetime pymongo
          
      - name: execute previsao_tempo_delta script 
        run: |
          python deltaclima/previsao_tempo_delta.py
